version: '3.8'

services:
  postgres-primary:
    image: postgres:16
    container_name: postgres-primary

    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: Admin_123
      POSTGRES_DB: url_shortener_db

    ports:
      - "5433:5432"

    command:
      - postgres
      - -c
      - wal_level=replica
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10
      - -c
      - hba_file=/etc/postgresql-custom/pg_hba.conf

    volumes:
      - primary_data:/var/lib/postgresql/data
      - ./postgres-replication/primary/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-replication/primary/pg_hba.conf:/etc/postgresql-custom/pg_hba.conf:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-replica:
    image: postgres:16
    container_name: postgres-replica
    user: postgres

    environment:
      PRIMARY_HOST: postgres-primary
      PRIMARY_PORT: 5432
      REPLICATOR_USER: replicator
      REPLICATOR_PASSWORD: replicator_password

    ports:
      - "5434:5432"

    entrypoint: ["bash", "/docker-entrypoint-replica.sh"]

    volumes:
      - replica_data:/var/lib/postgresql/data
      - ./postgres-replication/replica/init-replica.sh:/docker-entrypoint-replica.sh:ro

    depends_on:
      postgres-primary:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  redis:
    image: redis:latest
    container_name: url_shortener_redis
    ports:
      - "6379:6379"
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "3000:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     # - app
  #     - app1
  #     - app2
  #     - app3

  haproxy:
    image: haproxy:alpine
    container_name: url_shortener_haproxy
    ports:
      - "3000:3000"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app1
      - app2
      - app3

  app1:
    build: .
    environment:
      APP_VERSION: "v2"
      DB_USER: Admin
      DB_PASSWORD: Admin_123
      DB_NAME: url_shortener_db
      REDIS_HOST: redis
      REDIS_PORT: 6379

      DB_PRIMARY_HOST: postgres-primary
      DB_PRIMARY_PORT: 5432

      DB_REPLICA_HOST: postgres-replica
      DB_REPLICA_PORT: 5432
    expose:
      - "3000"
    depends_on:
      postgres-primary:
        condition: service_healthy
      postgres-replica:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    stop_grace_period: 20s

  app2:
    build: .
    environment:
      APP_VERSION: "v2"
      DB_USER: Admin
      DB_PASSWORD: Admin_123
      DB_NAME: url_shortener_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      HEALTH_FAIL: "false"

      DB_PRIMARY_HOST: postgres-primary
      DB_PRIMARY_PORT: 5432

      DB_REPLICA_HOST: postgres-replica
      DB_REPLICA_PORT: 5432

    expose:
      - "3000"
    depends_on:
      postgres-primary:
        condition: service_healthy
      postgres-replica:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    stop_grace_period: 20s

  app3:
    build: .
    environment:
      APP_VERSION: "v2"
      DB_USER: Admin
      DB_PASSWORD: Admin_123
      DB_NAME: url_shortener_db
      REDIS_HOST: redis
      REDIS_PORT: 6379


      DB_PRIMARY_HOST: postgres-primary
      DB_PRIMARY_PORT: 5432

      DB_REPLICA_HOST: postgres-replica
      DB_REPLICA_PORT: 5432

    expose:
      - "3000"
    depends_on:
      postgres-primary:
        condition: service_healthy
      postgres-replica:
        condition: service_healthy
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    stop_grace_period: 20s

  # app:
  #   build: .
  #   # container_name: url_shortener_app
  #   environment:
  #     DB_USER: Admin
  #     DB_PASSWORD: Admin_123
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_NAME: url_shortener_db
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #   expose:
  #     - "3000"
  #   # ports:
  #     # - "3001-3003:3000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: npm run test

volumes:
  primary_data:
  replica_data: