# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust

# App containers connecting over the docker network
host    all             all             0.0.0.0/0               scram-sha-256

# Replica streaming replication connections
host    replication     replicator      0.0.0.0/0               scram-sha-256
